# 用例基本信息
testinfo:
      id: test_addProject
      title: 添加项目
      host: ${test_platform}$
      address: /api/project/add_project

# 前置条件，case之前需关联的接口
premise:
      - test_name: 登陆1
        info: 正常登陆1
        host: ${test_platform}$
        address: /api/user/login
        http_type: http
        request_type: post
        parameter_type: form-data
        headers: {}
        timeout: 8
        parameter:
              username: litao
              password: lt19910301
        file: false
        relevance:  # 关联的键
              - key

# 测试用例
test_case:
    - test_name: 添加项目
      http_type: http
      request_type: post
      parameter_type: raw
      headers:
            Authorization: Token ${key}$
            Content-Type: application/json
      timeout: 8
      parameter:
            name: "123"
            type: Web
            version: abc
            description: abc
      file: false
      check:
            check_type: no_check # 不校验
            datebase:
            expected_code:
            expected_request:
      relevance:

    - test_name: 添加项目1
      info: 添加项目1
      http_type: http
      request_type: post
      parameter_type: raw
      headers:
            Authorization: Token ${key}$
            Content-Type: application/json
      timeout: 8
      parameter:
            name: "132"
            type: Web
            version: "321"
            description: "123"
      file: false
      check:
            check_type: only_check_status # 校验http状态
            datebase:
            expected_code: 200
            expected_request:
      relevance:

    - test_name: 添加项目2
      info: 添加项目2
      http_type: http
      request_type: post
      parameter_type: raw
      headers:
            Authorization: Token ${key}$
            Content-Type: application/json
      timeout: 8
      parameter:
            name: "132"
            type: "Web"
            version: "321"
            description: "123"
      file: false
      check:
            check_type: json # 校验json格式
            datebase:
            expected_code: 200
            expected_request: {"code":"999997","msg":"存在相同名称","data":null}
      relevance:

    - test_name: 添加项目3
      info: 添加项目3
      http_type: http
      request_type: post
      parameter_type: raw
      headers:
            Authorization: Token ${key}$
            Content-Type: application/json
      timeout: 8
      parameter:
            name: "132"
            type: Web
            version: "321"
            description: "123"
      file: false
      check:
            check_type: entirely_check # 完全校验
            datebase:
            expected_code: 200
            expected_request: {"code":"999997","msg":"存在相同名称","data":null}
      relevance:

    - test_name: 添加项目4
      info: 添加项目4
      http_type: http
      request_type: post
      parameter_type: raw
      headers:
            Authorization: Token ${key}$
            Content-Type: application/json
      timeout: 8
      parameter:
            name: "132"
            type: Web
            version: "321"
            description: "123"
      file: false
      check:
            check_type: Regular_check # 正则校验
            datebase:
            expected_code: 200
            expected_request:
                  - 存在相同名称
                  - msg
      relevance:

    - test_name: 添加项目5
      info: 添加项目5
      http_type: http
      request_type: post
      parameter_type: raw
      headers:
            Authorization: Token ${key}$
            Content-Type: application/json
      timeout: 8
      parameter:
            name: "132"
            type: "Web"
            version: "321"
            description: "123"
      file: false
      check:
            check_type: datebase_check # 数据库校验
            datebase:
                  NAME: api_test
                  USER: root
                  PASSWORD: lt19910301
                  PORT: 3306
                  sql: select * form api_test
            expected_code: 200
            expected_request:
      relevance:
